[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    titleAddition = "The democratization of the Age of Aquarius starts here."
    description = "The democratization of the Age of Aquarius starts here. Wheel of Heaven is a knowledge base exploring the working hypothesis that life on Earth was intelligently designed by an extraterrestrial civilization, the so-called Elohim."
    titleHome = "Wheel of Heaven"
    footer_head = "Embark on a journey into the Age of Aquarius with Wheel of Heaven, a portal of discovery and democratization of cosmic knowledge. Our platform delves into the compelling hypothesis that life on Earth was not a mere chance occurrence, but an act of intelligent design by an advanced extraterrestrial civilization known as the Elohim. Wheel of Heaven offers a rich knowledge base that intertwines ancient wisdom, modern scientific inquiry, and visionary insights, inviting you to explore the possibility of our celestial origins and the profound implications for our future."
    footer = "Made with â™¥ in Switzerland using <a href=\"https://github.com/wheelofheaven/\" class=\"link\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" class=\"link\" target=\"_blank\">Zola</a>, and <a href=\"https://getdoks.org/\" class=\"link\" target=\"_blank\">Doks</a>"
    alertText = "Welcome to Wheel of Heaven. Please note this website is being still improved on a daily basis. ğŸ˜Š"

[de]
  languageName = "Deutsch"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "DE"
    languageTag = "de-DE"
titleAddition = "Die Demokratisierung des Wassermannzeitalters ist hier."
    description = "Die Demokratisierung des Wassermannzeitalters ist hier. Wheel of Heaven ist eine sogenannte Knowledge Base, welche die Arbeitsthese vertritt, dass das Leben auf der Erde von einer auÃŸerirdischen Zivilisation, den sogenannten Elohim, geschaffen wurde."
    titleHome = "Wheel of Heaven"
    footer_head = "Begeben Sie sich auf eine Reise ins Zeitalter des Wassermanns mit Wheel of Heaven, einem Portal der Entdeckung und Demokratisierung kosmischen Wissens. Unsere Plattform erforscht die faszinierende Hypothese, dass das Leben auf der Erde kein Zufall war, sondern ein Akt des intelligenten Designs durch eine fortgeschrittene auÃŸerirdische Zivilisation, bekannt als die Elohim. Wheel of Heaven bietet eine reiche Wissensbasis, die altes Wissen, moderne wissenschaftliche Forschung und visionÃ¤re Einsichten verbindet und Sie einlÃ¤dt, die MÃ¶glichkeit unserer himmlischen UrsprÃ¼nge und die tiefgreifenden Implikationen fÃ¼r unsere Zukunft zu erforschen."
    footer = "Made with â™¥ in der Schweiz mithilfe von <a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>, und <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>"
    alertText = "Willkommen bei Wheel of Heaven. Bitte beachte dass diese Website sich noch im Bau befindet. ğŸ˜Š"

[es]
  languageName = "EspaÃ±ol"
  contentDir = "content/es"
  weight = 20
  [es.params]
    languageISO = "ES"
    languageTag = "es-ES"
titleAddition = "La democratizaciÃ³n de la Era de Acuario estÃ¡ aquÃ­."
    description = "La democratizaciÃ³n de la Era de Acuario estÃ¡ aquÃ­. Wheel of Heaven es una knowledge base alrededor de la teorÃ­a de trabajo de que la vida en la tierra fue diseÃ±ada de manera inteligente por una civilizaciÃ³n extraterrestre, el llamado Elohim."
    titleHome = "Wheel of Heaven"
    footer_head = "EmbÃ¡rcate en un viaje hacia la Era de Acuario con Wheel of Heaven, un portal de descubrimiento y democratizaciÃ³n del conocimiento cÃ³smico. Nuestra plataforma profundiza en la hipÃ³tesis fascinante de que la vida en la Tierra no fue una mera casualidad, sino un acto de diseÃ±o inteligente por una civilizaciÃ³n extraterrestre avanzada conocida como los Elohim. Wheel of Heaven ofrece una rica base de conocimientos que entrelaza la sabidurÃ­a antigua, la indagaciÃ³n cientÃ­fica moderna y percepciones visionarias, invitÃ¡ndote a explorar la posibilidad de nuestros orÃ­genes celestiales y las profundas implicaciones para nuestro futuro."
    footer = "Made with â™¥ en Suiza con <a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>, y <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>"
    alertText = "Bienvenido a Wheel of Heaven. Tenga en cuenta que este sitio web aÃºn se mejora a diario. ğŸ˜Š"


[fr]
  languageName = "FranÃ§ais"
  contentDir = "content/fr"
  weight = 25
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
titleAddition = "La dÃ©mocratisation de l'Ã‚ge du Verseau est lÃ ."
    description = "La dÃ©mocratisation de l'Ã‚ge du Verseau est lÃ . Wheel of Heaven est une knowledge base autour de la thÃ©orie de travail selon laquelle la vie sur terre a Ã©tÃ© intelligemment conÃ§ue par une civilisation extraterrestre, les soi-disant Elohim."
    titleHome = "Wheel of Heaven"
    footer_head = "Embarquez pour un voyage dans l'Ãˆre du Verseau avec Wheel of Heaven, un portail de dÃ©couverte et de dÃ©mocratisation du savoir cosmique. Notre plateforme se penche sur l'hypothÃ¨se captivante que la vie sur Terre n'est pas un simple hasard, mais le fruit d'une conception intelligente par une civilisation extraterrestre avancÃ©e, connue sous le nom d'Elohim. Wheel of Heaven offre une base de connaissances enrichissante qui entrelace sagesse ancienne, enquÃªte scientifique moderne et perspectives visionnaires, vous invitant Ã  explorer la possibilitÃ© de nos origines cÃ©lestes et les implications profondes pour notre avenir."
    footer = "Made with â™¥ en Suisse avec <a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>, et <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>"
    alertText = "Bienvenue chez Wheel of Heaven. Veuillez noter que ce site web est encore amÃ©liorÃ© quotidiennement. ğŸ˜Š"

[ja]
  languageName = "æ—¥æœ¬èª"
  contentDir = "content/ja"
  weight = 30
  [ja.params]
    languageISO = "JA"
    languageTag = "ja-JA"
    titleAddition = "æ°´ç“¶åº§ã®æ™‚ä»£ã®æ°‘ä¸»åŒ–ãŒã“ã“ã«ã‚ã‚Šã¾ã™ã€‚"
    description = "æ°´ç“¶åº§ã®æ™‚ä»£ã®æ°‘ä¸»åŒ–ãŒã“ã“ã«ã‚ã‚Šã¾ã™ã€‚ Wheel of Heaven ã¯ã€åœ°çƒä¸Šã®ç”Ÿå‘½ã¯åœ°çƒå¤–æ–‡æ˜ã€ã„ã‚ã‚†ã‚‹ã‚¨ãƒ­ãƒ’ãƒ ã«ã‚ˆã£ã¦çŸ¥çš„ã«è¨­è¨ˆã•ã‚ŒãŸã¨ã„ã†ä½œæ¥­ç†è«–ã«é–¢ã™ã‚‹çŸ¥è­˜ãƒ™ãƒ¼ã‚¹ã§ã™ã€‚"
    titleHome = "Wheel of Heaven"
    footer_head = "Wheel of Heavenã§ã¯æ°´ç“¶åº§ã®æ™‚ä»£ã¸ã®æ—…ãŒå§‹ã¾ã‚Šã¾ã™ã€‚ç™ºè¦‹ã¨å®‡å®™çŸ¥è­˜ã®æ°‘ä¸»åŒ–ã®ãƒãƒ¼ã‚¿ãƒ«ã§ã™ã€‚ç§ãŸã¡ã®ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ ã¯ã€åœ°çƒä¸Šã®ç”Ÿå‘½ãŒå¶ç„¶ã§ã¯ãªãã€ã‚¨ãƒ­ãƒ’ãƒ ã¨ã—ã¦çŸ¥ã‚‰ã‚Œã‚‹é€²ã‚“ã å®‡å®™æ–‡æ˜ã«ã‚ˆã‚‹ã‚¤ãƒ³ãƒ†ãƒªã‚¸ã‚§ãƒ³ãƒˆãƒ‡ã‚¶ã‚¤ãƒ³ã®ç”£ç‰©ã§ã‚ã‚‹ã¨ã„ã†é­…åŠ›çš„ãªä»®èª¬ã‚’æ¢æ±‚ã—ã¾ã™ã€‚Wheel of Heavenã¯ã€å¤ä»£ã®çŸ¥æµã€ç¾ä»£ã®ç§‘å­¦çš„æ¢æ±‚ã€ãã—ã¦å…ˆè¦‹ã®æ˜ã‚’çµ„ã¿åˆã‚ã›ãŸè±Šã‹ãªçŸ¥è­˜åŸºç›¤ã‚’æä¾›ã—ã€æˆ‘ã€…ã®å¤©ã®èµ·æºã¨æœªæ¥ã«å¯¾ã™ã‚‹æ·±ã„æ„å‘³ã‚’æ¢æ±‚ã™ã‚‹ã“ã¨ã‚’ãŠèª˜ã„ã—ã¾ã™ã€‚"
    footer = "<a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>ã€<a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>ã€<a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a> ã‚’ä½¿ç”¨ã—ã¦ã‚¹ã‚¤ã‚¹ã§ â™¥ ã§ä½œæˆ"
    alertText = "Wheel of Heaven ã¸ã‚ˆã†ã“ãã€‚ ã“ã®ã‚¦ã‚§ãƒ–ã‚µã‚¤ãƒˆã¯ç¾åœ¨ã‚‚æ—¥ã€…æ”¹å–„ã•ã‚Œã¦ã„ã‚‹ã“ã¨ã«æ³¨æ„ã—ã¦ãã ã•ã„ã€‚ ğŸ˜Š"

[ru]
  languageName = "PÑƒÑÑĞºĞ¸Ğ¹"
  contentDir = "content/ru"
  weight = 35
  [ru.params]
    languageISO = "RU"
    languageTag = "ru-RU"
titleAddition = "Ğ”ĞµĞ¼Ğ¾ĞºÑ€Ğ°Ñ‚Ğ¸Ğ·Ğ°Ñ†Ğ¸Ñ ÑĞ¿Ğ¾Ñ…Ğ¸ Ğ’Ğ¾Ğ´Ğ¾Ğ»ĞµÑ Ğ·Ğ´ĞµÑÑŒ."
    description = "Ğ”ĞµĞ¼Ğ¾ĞºÑ€Ğ°Ñ‚Ğ¸Ğ·Ğ°Ñ†Ğ¸Ñ ÑĞ¿Ğ¾Ñ…Ğ¸ Ğ’Ğ¾Ğ´Ğ¾Ğ»ĞµÑ Ğ·Ğ´ĞµÑÑŒ. Wheel of Heaven-ÑÑ‚Ğ¾ Ğ±Ğ°Ğ·Ğ° Ğ·Ğ½Ğ°Ğ½Ğ¸Ğ¹ Ğ²Ğ¾ĞºÑ€ÑƒĞ³ Ñ€Ğ°Ğ±Ğ¾Ñ‡ĞµĞ¹ Ñ‚ĞµĞ¾Ñ€Ğ¸Ğ¸, Ñ‡Ñ‚Ğ¾ Ğ¶Ğ¸Ğ·Ğ½ÑŒ Ğ½Ğ° Ğ—ĞµĞ¼Ğ»Ğµ Ğ±Ñ‹Ğ»Ğ° Ñ€Ğ°Ğ·ÑƒĞ¼Ğ½Ğ¾ Ñ€Ğ°Ğ·Ñ€Ğ°Ğ±Ğ¾Ñ‚Ğ°Ğ½Ğ° Ğ²Ğ½ĞµĞ·ĞµĞ¼Ğ½Ğ¾Ğ¹ Ñ†Ğ¸Ğ²Ğ¸Ğ»Ğ¸Ğ·Ğ°Ñ†Ğ¸ĞµĞ¹, Ñ‚Ğ°Ğº Ğ½Ğ°Ğ·Ñ‹Ğ²Ğ°ĞµĞ¼Ñ‹Ğ¼ Elohim."
    titleHome = "Wheel of Heaven"
    footer_head = "ĞŸÑƒÑ‚ĞµÑˆĞµÑÑ‚Ğ²Ğ¸Ğµ Ğ² Ğ­Ñ€Ñƒ Ğ’Ğ¾Ğ´Ğ¾Ğ»ĞµÑ Ğ½Ğ°Ñ‡Ğ¸Ğ½Ğ°ĞµÑ‚ÑÑ Ğ·Ğ´ĞµÑÑŒ, Ğ½Ğ° Wheel of Heaven - Ğ¿Ğ¾Ñ€Ñ‚Ğ°Ğ»Ğµ Ğ¾Ñ‚ĞºÑ€Ñ‹Ñ‚Ğ¸Ğ¹ Ğ¸ Ğ´ĞµĞ¼Ğ¾ĞºÑ€Ğ°Ñ‚Ğ¸Ğ·Ğ°Ñ†Ğ¸Ğ¸ ĞºĞ¾ÑĞ¼Ğ¸Ñ‡ĞµÑĞºĞ¸Ñ… Ğ·Ğ½Ğ°Ğ½Ğ¸Ğ¹. ĞĞ°ÑˆĞ° Ğ¿Ğ»Ğ°Ñ‚Ñ„Ğ¾Ñ€Ğ¼Ğ° Ğ¸ÑÑĞ»ĞµĞ´ÑƒĞµÑ‚ ÑƒĞ²Ğ»ĞµĞºĞ°Ñ‚ĞµĞ»ÑŒĞ½ÑƒÑ Ğ³Ğ¸Ğ¿Ğ¾Ñ‚ĞµĞ·Ñƒ Ğ¾ Ñ‚Ğ¾Ğ¼, Ñ‡Ñ‚Ğ¾ Ğ¶Ğ¸Ğ·Ğ½ÑŒ Ğ½Ğ° Ğ—ĞµĞ¼Ğ»Ğµ Ğ½Ğµ ÑĞ²Ğ»ÑĞµÑ‚ÑÑ ÑĞ»ÑƒÑ‡Ğ°Ğ¹Ğ½Ğ¾ÑÑ‚ÑŒÑ, Ğ° ÑĞ²Ğ»ÑĞµÑ‚ÑÑ Ñ€ĞµĞ·ÑƒĞ»ÑŒÑ‚Ğ°Ñ‚Ğ¾Ğ¼ Ğ¸Ğ½Ñ‚ĞµĞ»Ğ»ĞµĞºÑ‚ÑƒĞ°Ğ»ÑŒĞ½Ğ¾Ğ³Ğ¾ Ğ´Ğ¸Ğ·Ğ°Ğ¹Ğ½Ğ° Ñ€Ğ°Ğ·Ğ²Ğ¸Ñ‚Ğ¾Ğ¹ Ğ²Ğ½ĞµĞ·ĞµĞ¼Ğ½Ğ¾Ğ¹ Ñ†Ğ¸Ğ²Ğ¸Ğ»Ğ¸Ğ·Ğ°Ñ†Ğ¸Ğ¸, Ğ¸Ğ·Ğ²ĞµÑÑ‚Ğ½Ğ¾Ğ¹ ĞºĞ°Ğº Ğ­Ğ»Ğ¾Ñ…Ğ¸Ğ¼. Wheel of Heaven Ğ¿Ñ€ĞµĞ´Ğ»Ğ°Ğ³Ğ°ĞµÑ‚ Ğ±Ğ¾Ğ³Ğ°Ñ‚ÑƒÑ Ğ±Ğ°Ğ·Ñƒ Ğ·Ğ½Ğ°Ğ½Ğ¸Ğ¹, ÑĞ¾Ñ‡ĞµÑ‚Ğ°ÑÑ‰ÑƒÑ Ğ´Ñ€ĞµĞ²Ğ½ÑÑ Ğ¼ÑƒĞ´Ñ€Ğ¾ÑÑ‚ÑŒ, ÑĞ¾Ğ²Ñ€ĞµĞ¼ĞµĞ½Ğ½Ñ‹Ğµ Ğ½Ğ°ÑƒÑ‡Ğ½Ñ‹Ğµ Ğ¸ÑÑĞ»ĞµĞ´Ğ¾Ğ²Ğ°Ğ½Ğ¸Ñ Ğ¸ Ğ¿Ñ€Ğ¾Ğ³Ñ€ĞµÑÑĞ¸Ğ²Ğ½Ñ‹Ğµ Ğ¸Ğ´ĞµĞ¸, Ğ¿Ñ€Ğ¸Ğ³Ğ»Ğ°ÑˆĞ°Ñ Ğ²Ğ°Ñ Ğ¸ÑÑĞ»ĞµĞ´Ğ¾Ğ²Ğ°Ñ‚ÑŒ Ğ²Ğ¾Ğ·Ğ¼Ğ¾Ğ¶Ğ½Ğ¾ÑÑ‚ÑŒ Ğ½Ğ°ÑˆĞµĞ³Ğ¾ Ğ½ĞµĞ±ĞµÑĞ½Ğ¾Ğ³Ğ¾ Ğ¿Ñ€Ğ¾Ğ¸ÑÑ…Ğ¾Ğ¶Ğ´ĞµĞ½Ğ¸Ñ Ğ¸ Ğ³Ğ»ÑƒĞ±Ğ¾ĞºĞ¸Ğµ Ğ¿Ğ¾ÑĞ»ĞµĞ´ÑÑ‚Ğ²Ğ¸Ñ Ğ´Ğ»Ñ Ğ½Ğ°ÑˆĞµĞ³Ğ¾ Ğ±ÑƒĞ´ÑƒÑ‰ĞµĞ³Ğ¾."
    footer = "Made with â™¥ Ğ² Ğ¨Ğ²ĞµĞ¹Ñ†Ğ°Ñ€Ğ¸Ğ¸ <a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>, <a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a>, Ğ¸ <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>"
    alertText = "Ğ”Ğ¾Ğ±Ñ€Ğ¾ Ğ¿Ğ¾Ğ¶Ğ°Ğ»Ğ¾Ğ²Ğ°Ñ‚ÑŒ Ğ² Wheel of Heaven. ĞĞ±Ñ€Ğ°Ñ‚Ğ¸Ñ‚Ğµ Ğ²Ğ½Ğ¸Ğ¼Ğ°Ğ½Ğ¸Ğµ, Ñ‡Ñ‚Ğ¾ ÑÑ‚Ğ¾Ñ‚ Ğ²ĞµĞ±-ÑĞ°Ğ¹Ñ‚ ĞµĞ¶ĞµĞ´Ğ½ĞµĞ²Ğ½Ğ¾ ÑĞ¾Ğ²ĞµÑ€ÑˆĞµĞ½ÑÑ‚Ğ²ÑƒĞµÑ‚ÑÑ. ğŸ˜Š"

[zh]
  languageName = "ä¸­æ–‡"
  contentDir = "content/zh"
  weight = 40
  [zh.params]
    languageISO = "ZH"
    languageTag = "zh-CN"
titleAddition = "æ°´ç“¶åº§æ—¶ä»£çš„æ°‘ä¸»åŒ–å°±åœ¨è¿™é‡Œã€‚"
    description = "æ°´ç“¶åº§æ—¶ä»£çš„æ°‘ä¸»åŒ–å°±åœ¨è¿™é‡Œã€‚ å¤©å ‚æ˜¯å›´ç»•ç€å·¥ä½œç†è®ºçš„çŸ¥è¯†åŸºç¡€ï¼Œå³åœ°çƒä¸Šçš„ç”Ÿå‘½æ˜¯ç”±å¤–æ˜Ÿæ–‡æ˜æ™ºèƒ½è®¾è®¡çš„ï¼Œå³æ‰€è°“çš„åŸƒæ´›å› ï¼ˆElohimï¼‰ã€‚"
    titleHome = "Wheel of Heaven"
    footer_head = "æ°´ç“¶æ—¶ä»£çš„æ°‘ä¸»åŒ–åœ¨è¿™é‡Œå¼€å§‹ã€‚Wheel of Heavenæ˜¯ä¸€ä¸ªæ¢ç´¢çŸ¥è¯†çš„åŸºåœ°ï¼Œå®ƒæ¢è®¨çš„æ ¸å¿ƒå‡è®¾æ˜¯åœ°çƒä¸Šçš„ç”Ÿå‘½æ˜¯ç”±ä¸€ç§é«˜çº§å¤–æ˜Ÿæ–‡æ˜â€”â€”æ‰€è°“çš„Elohimâ€”â€”æ™ºèƒ½è®¾è®¡çš„ã€‚æˆ‘ä»¬çš„å¹³å°æ·±å…¥æ¢è®¨è¿™ä¸€è¿·äººçš„å‡è®¾ï¼Œå°†å¤ä»£æ™ºæ…§ã€ç°ä»£ç§‘å­¦æ¢ç´¢å’Œå‰ç»æ€§æ´å¯Ÿäº¤ç»‡åœ¨ä¸€èµ·ï¼Œé‚€è¯·æ‚¨æ¢ç´¢æˆ‘ä»¬çš„å¤©ä½“èµ·æºå’Œå¯¹æˆ‘ä»¬æœªæ¥çš„æ·±è¿œå½±å“ã€‚"
    footer = "ä½¿ç”¨<a href=\"https://github.com/wheelofheaven/\" target=\"_blank\">Github</a>ï¼Œ<a href=\"https://www.getzola.org/\" target=\"_blank\">Zola</a> å’Œ <a href=\"https://getdoks.org/\" target=\"_blank\">Doks</a> åœ¨ç‘å£«åˆ¶é€ â™¥"
    alertText = "æ¬¢è¿æ¥åˆ° Wheel of Heaven (â€œå¤©è½®â€)ã€‚ è¯·æ³¨æ„ï¼Œè¯¥ç½‘ç«™æ¯å¤©éƒ½åœ¨æ”¹è¿›ã€‚ ğŸ˜Š"

